In [14]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
# 3층 신경망 구현하기
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def identity(x):
    return x


X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

# 단순 행렬 모양 출력
print(W1.shape)
print(X.shape)
print(B1.shape)

# 행렬 곱 연산
A1 = np.dot(X, W1) + B1
print(A1.shape)
print(A1)

# 시그모이드 함수 적용
Z1 = sigmoid(A1)

print(A1)
print(Z1)

W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3) + B3
Y = identity(A3)

print(A3)

(2, 3)
(2,)
(3,)
(3,)
[0.3 0.7 1.1]
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
(3,)
(3, 2)
(2,)
[0.31682708 0.69627909]


In [16]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def identity(x):
    return x


def init_network():
    network = {
        "W1": np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]),
        "b1": np.array([0.1, 0.2, 0.3]),
        "W2": np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]]),
        "b2": np.array([0.1, 0.2]),
        "W3": np.array([[0.1, 0.3], [0.2, 0.4]]),
        "b3": np.array([0.1, 0.2])
    }
    return network


def forward(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity(a3)
    return y

# 가중치와 편향을 생성
network = init_network()
x = np.array([1.0, 0.5])
# 입력 신호를 출력으로 변환하는 처리 과정 구현
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
